In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

### 1. Вектора

In [6]:

y = np.array([[1],[2],[4]],float)
print(x.shape)
print(y.shape)

(1, 3)
(3, 1)


In [7]:
x + 2

array([[3., 4., 5.]])

In [8]:
x * 2

array([[2., 4., 6.]])

In [9]:
x.transpose()

array([[1.],
       [2.],
       [3.]])

In [10]:
x*y

array([[ 1.,  2.,  3.],
       [ 2.,  4.,  6.],
       [ 4.,  8., 12.]])

In [11]:
e = np.identity(5)

In [12]:
5*e

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

In [13]:
p = np.linalg.inv(5*e)
p

array([[0.2, 0. , 0. , 0. , 0. ],
       [0. , 0.2, 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. , 0. ],
       [0. , 0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. , 0.2]])

### 2. Детерминант

In [14]:
x = np.array([[1,2,3],[4,0,6],[7,8,9]],float)

In [15]:
np.linalg.det(x)

59.999999999999986

In [16]:
det = 1*(0*9-8*6)-2*(4*9-7*6)+3*(4*8-7*0)
det

60

### 3. Обращение матрицы

In [17]:
x = np.array([[1,2,3],[4,0,6],[7,8,9]],float)

In [21]:
np.linalg.inv(x)

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [27]:
M = np.array([[0*9-8*6, 4*9-7*6, 4*8-7*0],[2*9-8*3, 1*9-7*3, 1*8-2*7],[2*6-0*3, 1*6-4*3, 1*0-4*2]])
M

array([[-48,  -6,  32],
       [ -6, -12,  -6],
       [ 12,  -6,  -8]])

In [26]:
A = np.array([[0*9-8*6, -(4*9-7*6), 4*8-7*0],[-(2*9-8*3), 1*9-7*3, -(1*8-2*7)],[2*6-0*3, -(1*6-4*3), 1*0-4*2]])
A

array([[-48,   6,  32],
       [  6, -12,   6],
       [ 12,   6,  -8]])

In [30]:
At = np.transpose(A)
At

array([[-48,   6,  12],
       [  6, -12,   6],
       [ 32,   6,  -8]])

In [32]:
Ao = At/det
Ao

array([[-0.8       ,  0.1       ,  0.2       ],
       [ 0.1       , -0.2       ,  0.1       ],
       [ 0.53333333,  0.1       , -0.13333333]])

In [22]:
y = np.array([[1,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],float)

In [23]:
np.linalg.matrix_rank(y)

1

### 4. Векторная алгебра.

In [35]:
a = np.array([1,5],float)
b = np.array([2,8],float)
a,b

(array([1., 5.]), array([2., 8.]))

In [36]:
s = np.inner(a,b)
s/(np.linalg.norm(a)*np.linalg.norm(b))

0.9988681377244377

### 5. Векторное произведение

In [39]:
a = np.array([1,5,0],float)
b = np.array([2,8,7],float)
c = np.array([7,1.5,3],float)
v = np.cross(a,b)
print(np.inner(v,c))

228.5
