### Практическое задание NumPy

### Задание 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [18]:
import numpy as np

Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [22]:
a = np.arange(12,24)

In [25]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
print(type(a))

<class 'numpy.ndarray'>


Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. 

In [29]:
np.reshape(a,(3,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [30]:
np.reshape(a,(4,3))

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [32]:
np.reshape(a,(12,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [33]:
np.reshape(a,(6,2))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [35]:
np.reshape(a,(1,12))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [37]:
np.reshape(a,(3,-1))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [41]:
np.reshape(a,(1,-1))

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
np.reshape(a,(6,-1))

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [42]:
np.reshape(a,(-1,4))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [43]:
np.reshape(a,(-1,1))

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
### Да

### Задание 2

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения  со средним, равным 0 и среднеквадратичным отклонением, равным 1.0.

In [50]:
a = np.random.sample((3, 4))
print(a)

[[0.3793254  0.53517683 0.12376119 0.40719178]
 [0.44496445 0.98096788 0.37462104 0.92555589]
 [0.28599667 0.48344719 0.41334142 0.18789918]]


Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [52]:
np.reshape(a,(1,-1))

array([[0.3793254 , 0.53517683, 0.12376119, 0.40719178, 0.44496445,
        0.98096788, 0.37462104, 0.92555589, 0.28599667, 0.48344719,
        0.41334142, 0.18789918]])

### Задание 3
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2

In [58]:
a = np.arange(20, 0, -2)
a

[20 18 16 14 12 10  8  6  4  2]


Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 

In [63]:
b = np. arange(20,1,-2).reshape(1,10)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


В чем разница между массивами a и b?

a - одномерный массив, b - двумерный состоящий из 1 строки и 10 столбцов

### Задание 4
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
### Не понял как может и больше и меньше 1


In [83]:
a = np.ones((2, 2))


In [84]:
b = np.zeros((3, 2))


In [85]:
v = np.vstack((a, b))
v.size

10

### Задание 5
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

In [92]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

In [91]:
A = np.reshape(a,(4,3))
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Получить матрицу At путем транспонирования матрицы A.

In [93]:
At = A.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [95]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
### размер 4*4. Нет, потому что квадратичная, хотя ошибки не будет просто будет такая же матрица

In [96]:
B.transpose()

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

### Задание 6
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [97]:
np.random.seed(42)

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [98]:
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C. 

In [119]:
C = np.reshape(c,(4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [100]:
D = (B + C) * 10
D

array([[ 110,  170,  350,  460],
       [ 240,  570,  980, 1260],
       [ 290,  950, 1510, 2180],
       [ 420, 1320, 2190, 3060]])

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [105]:
np.linalg.det(D)

-471959999.9999996

In [106]:
np.linalg.matrix_rank(D)

4

In [108]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01348843,  0.0079583 ,  0.01798881, -0.01812018],
       [-0.01714976,  0.01400966,  0.0147343 , -0.0136876 ],
       [-0.00575896,  0.00122044, -0.02040427,  0.01489957],
       [ 0.00966819, -0.00800915,  0.00577803, -0.00194508]])

### Задание 7
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 

In [115]:
D_inv = np.where(D_inv > 0, np.ones((4, 4)), np.zeros((4,4)))
D_inv

array([[1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [117]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212,   4]])